export enum ApprovalRequestStatus {
    NOT_SUBMITTED = "NOT_SUBMITTED",
    SUBMITTED = "SUBMITTED",
    SUBMITTED_TO_HR = "SUBMITTED_TO_HR",
    APPROVED = "APPROVED",
    DECLINED = "DECLINED",
    SUBMITTED_TO_HQ = "SUBMITTED_TO_HQ",
    AUTO_APPROVED = "AUTO_APPROVED",
}
