export enum ApprovalItemObject {
    PLAN_YEAR = "PLAN_YEAR",
    ENROLLMENT_PERIOD = "ENROLLMENT_PERIOD",
    PLAN = "PLAN",
    PRODUCT = "PRODUCT",
    PLAN_PRICE = "PLAN_PRICE",
    PLAN_RATE = "PLAN_RATE",
    PRICING_ELIGIBILITY = "PRICING_ELIGIBILITY",
    CARRIER_FORMS = "CARRIER_FORMS",
    BENEFIT_DOLLARS = "BENEFIT_DOLLARS",
}
