export const AccountTypeFilterDropdownData = [
    { name: "Payroll", value: "PAYROLL" },
    { name: "Payroll - Direct Bill", value: "PAYROLLDIRECTBILL" },
    { name: "Payroll - EBS", value: "PAYROLL_EBS" },
    { name: "Payroll Large", value: "PAYROLL_LARGE" },
    { name: "Payroll Large - Direct Bill", value: "PAYROLLDIRECTBILL_LARGE" },
    { name: "Labor Union", value: "UNION" },
    { name: "Labor Union - List Bill", value: "UNION_LISTBILL" },
    { name: "Association", value: "ASSOCIATION" },
    { name: "Association – List Bill", value: "ASSOCIATION_LISTBILL" },
    { name: "Credit Union - Payroll", value: "PAYROLLDIRECTBILL_ACH" },
    { name: "Credit Union - Non-Payroll", value: "NONPAYROLL_ACH" },
    { name: "Credit Union - Association", value: "ASSOCIATION_ACH" },
    { name: "Non-Payroll", value: "NONPAYROLL" },
    { name: "Non-Payroll - List bill", value: "NONPAYROLL_LISTBILL" },
];
