export enum Characteristics {
    COMPANY_PROVIDED = "COMPANY_PROVIDED",
    AUTOENROLLABLE = "AUTOENROLLABLE",
    SUPPLEMENTARY = "SUPPLEMENTARY",
    STACKABLE = "STACKABLE",
    DECLINE = "DECLINE",
}
