export enum CoverageStartOptions {
    DAILY = "DAILY",
    FIRST = "FIRST",
    FIRST_FIFTEENTH = "FIRST_FIFTEENTH",
}
export enum AflacGroupPlanYearType {
    AFLAC_INDIVIDUAL = "AFLAC_INDIVIDUAL",
    AFLAC_GROUP = "AFLAC_GROUP",
}
export enum AflacGroupOfferingError {
    CARRIER_APPOINTMENT = "CARRIER_APPOINTMENT",
    WRITING_NUMBER = "WRITING_NUMBER",
    APPLICATION_ORIGIN = "APPLICATION_ORIGIN",
    SITUS_STATE_MISMATCH = "SITUS_STATE_MISMATCH",
    PRODUCT_MISMATCH = "PRODUCT_MISMATCH",
    NON_SELF_SERVICE_PRODUCTS = "NON_SELF_SERVICE_PRODUCTS",
    AFLAC_API_ERROR = "AFLAC_API_ERROR",
    COVERAGE_PERIOD_PAST_DATE = "COVERAGE_PERIOD_PAST_DATE",
}
