export type DependencyType =
    | "REQUIRES_ENROLLMENT_IN_ANOTHER_PLAN"
    | "REQUIRES_NONENROLLMENT_IN_ANOTHER_PLAN"
    | "REQUIRES_ELIGIBLE_SPOUSE"
    | "REQUIRES_BROKERS_PLAN_SELECTION"
    | "REQUIRES_NON_GI_PARENT_ENROLLMENT"
    | "REQUIRES_GI_PARENT_ENROLLMENT"
    | "REQUIRES_ELIGIBLE_CHILD"
    | "REQUIRES_NONSELECTION_IN_ANOTHER_PLAN"
    | "REQUIRES_SELECTION_IN_ANOTHER_PLAN";
