export enum DisableType {
    KNOCKOUT = "KNOCKOUT",
    SPOUSE_KNOCKOUT = "SPOUSE_KNOCKOUT",
    GENERIC = "GENERIC",
    MISSING_INFO = "MISSING_INFO",
    AGENT_ASSISTANCE = "AGENT_ASSISTANCE",
    PLAN_DEPENDENCY = "PLAN_DEPENDENCY",
    VCC_DISABILITY_DEPENDENCY = "VCC_DISABILITY_DEPENDENCY",
}
