export enum EbsPaymentOnFileEnum {
    CREDIT_CARD_PRESENT = "CREDIT_CARD_PRESENT",
    CREDIT_CARD_MISSING = "CREDIT_CARD_MISSING",
    BANK_INFORMATION_PRESENT = "BANK_INFORMATION_PRESENT",
    DIRECT_DEPOSIT = "DIRECT_DEPOSIT",
    TO_BE_DETERMINED = "TO_BE_DETERMINED",
    BANK_INFORMATION_MISSING = "BANK_INFORMATION_MISSING",
}
