export enum EnrollmentMethod {
    SELF_SERVICE = "SELF_SERVICE",
    FACE_TO_FACE = "FACE_TO_FACE",
    HEADSET = "HEADSET",
    CALL_CENTER = "CALL_CENTER",
    PIN_SIGNATURE = "PIN_SIGNATURE",
    VIRTUAL_FACE_TO_FACE = "VIRTUAL_FACE_TO_FACE",
    TELEPHONE_ENROLLMENT = "TELEPHONE_ENROLLMENT",
    VIRTUAL_F2F = "VIRTUAL_F2F",
}
