export enum KnockoutType {
    KNOCKOUT = "KNOCKOUT",
    SPOUSE_KNOCKOUT = "SPOUSE_KNOCKOUT",
    NOT_APPLICABLE = "NOT_APPLICABLE",
    PROPOSED_INSURED = "PROPOSED_INSURED",
    SPOUSE = "SPOUSE",
    CHILD = "CHILD",
    CHILD_KNOCKOUT = "CHILD_KNOCKOUT",
}
