export enum PrimaryLanguage {
    PRIMARY_BENEFITS_OFFERING_RESTRICTED_STATE_NON_TPI = "primary.portal.benefitsOffering.nonTpi.selfServiceEnrollment",
}

export enum SecondaryLanguage {
    SERVICE_UNAVAILABLE = "secondary.portal.qle.updateQle.serviceUnavailable",
}

export enum MessageCenterLanguage {
    MESSAGE_CENTER_COMPOSE_BUTTON = "primary.portal.messageCenter.composeButton",
    MESSAGE_CENTER_COMPOSE_FILE_UPLOAD_LABEL = "primary.portal.messageCenter.compose.fileUpload.label",
    MESSAGE_CENTER_COMPOSE_FILE_UPLOAD_HINT = "primary.portal.messageCenter.compose.fileUpload.hint",
    MESSAGE_CENTER_SINGLE_RECIPIENT_INPUT_ADMIN_HINT = "primary.portal.messageCenter.singleRecipient.adminsHint",
    MESSAGE_CENTER_ATTACHMENTS_BUTTON_VIEW = "primary.portal.messageCenter.messageAttachments.view",
    MESSAGE_CENTER_ATTACHMENTS_TYPE_LINK = "primary.portal.messageCenter.messageAttachments.linkPrefix",
    MESSAGE_CENTER_DASHBOARD_HEADER = "primary.portal.messageCenter.menu.header",
    MESSAGE_CENTER_DASHBOARD_INBOX = "primary.portal.messageCenter.menu.inbox",
    MESSAGE_CENTER_DASHBOARD_SETTINGS = "primary.portal.messageCenter.menu.settings",
    MESSAGE_DETAIL_FILE_UPLOAD_LABEL = "primary.portal.messageCenter.compose.fileUpload.label",
    MESSAGE_DETAIL_FILE_UPLOAD_HINT = "primary.portal.messageCenter.compose.fileUpload.hint",
    MESSAGE_DETAIL_BUTTON_REPLY_TOOLTIP = "primary.portal.messageCenter.messageDetail.button.reply.tooltip",
    MESSAGE_DETAIL_BUTTON_CLOSE = "primary.portal.messageCenter.messageDetail.button.close",
    MESSAGE_DETAIL_BUTTON_SEND = "primary.portal.messageCenter.messageDetail.button.send",
    MESSAGE_DETAIL_MESSAGE_LABEL = "primary.portal.messageCenter.messageDetail.message.label",
    MESSAGE_DETAIL_ERROR_MESSAGE_REQUIRED = "primary.portal.messageCenter.messageDetail.message.error.required",
    MESSAGE_DETAIL_BUTTON_REPLY = "primary.portal.messageCenter.messageDetail.button.reply",
    MESSAGE_DETAIL_BUTTON_DELETE = "primary.portal.messageCenter.messageDetail.button.delete",
    MESSAGE_DETAIL_BUTTON_RECALL = "primary.portal.messageCenter.messageDetail.button.recall",
    MESSAGE_DETAIL_BUTTON_MOVE = "primary.portal.messageCenter.messageDetail.button.move",
    MESSAGE_DETAIL_ALERT_READ = "primary.portal.messageCenter.messageDetail.alert.read",
    MESSAGE_DETAIL_ALERT_RECALL_SINGLE = "primary.portal.messageCenter.messageDetail.alert.recall.single",
    MESSAGE_DETAIL_ALERT_RECALL_PLURAL = "primary.portal.messageCenter.messageDetail.alert.recall.plural",
    MESSAGE_DETAIL_ALERT_RECALL_RECIPIENTS = "primary.portal.messageCenter.messageDetail.alert.recall.recipients",
    MESSAGE_DETAIL_LABEL_ATTACHMENTS = "primary.portal.messageCenter.messageDetail.attachments.label",
    MESSAGE_DETAIL_LABEL_NOTES = "primary.portal.messageCenter.messageDetail.notes.label",
    MESSAGE_DETAIL_BUTTON_REMOVE_NOTE = "primary.portal.messageCenter.messageDetail.notes.remove",
    MESSAGE_DETAIL_BUTTON_EDIT_NOTE = "primary.portal.messageCenter.messageDetail.notes.edit",
    MESSAGE_DETAIL_META_NOTES_POST_BY = "primary.portal.messageCenter.messageDetail.notes.meta.postBy",
    MESSAGE_DETAIL_META_NOTES_ON = "primary.portal.messageCenter.messageDetail.notes.meta.on",
    MESSAGE_DETAIL_BUTTON_ADD_NOTE = "primary.portal.messageCenter.messageDetail.notes.add",
    MESSAGE_DETAIL_HEADER_SENT = "primary.portal.messageCenter.messageDetail.header.sent",
    MESSAGE_DETAIL_HEADER_DELETE = "primary.portal.messageCenter.messageDetail.header.delete",
    MESSAGE_DETAIL_HEADER_REPLY = "primary.portal.messageCenter.messageDetail.header.reply",
    MESSAGE_DETAIL_HEADER_READ = "primary.portal.messageCenter.messageDetail.header.read",
    META_LABEL_CHANGE = "primary.portal.messageCenter.metaLabel.change",
    REPLY_META_TO = "primary.portal.messageCenter.metaLabel.to",
    REPLY_META_SUBJECT = "primary.portal.messageCenter.metaLabel.subject",
    REPLY_META_CATEGORY = "primary.portal.messageCenter.metaLabel.category",
    THREAD_META_LABEL_TO = "primary.portal.messageCenter.metaLabel.to",
    THREAD_META_LABEL_CATEGORY = "primary.portal.messageCenter.metaLabel.category",
    THREAD_META_LABEL_FROM = "primary.portal.messageCenter.metaLabel.from",
    THREAD_META_LABEL_STATUS = "primary.portal.messageCenter.metaLabel.status",
    THREAD_META_LABEL_ASSIGNED_ADMIN = "primary.portal.messageCenter.metaLabel.assignedAdmin",
    THREAD_META_LABEL_SUBJECT = "primary.portal.messageCenter.metaLabel.subject",
    THREAD_META_LABEL_SENT = "primary.portal.messageCenter.metaLabel.sent",
    THREAD_META_LABEL_CHANGE = "primary.portal.messageCenter.metaLabel.change",
    THREAD_META_LABEL_ASSIGN_ADMIN = "primary.portal.messageCenter.metaLabel.assignAdmin",
    ADMIN_ROLES_MODAL_HEADER = "primary.portal.messageCenter.modals.adminRoles.header",
    ADMIN_ROLES_MODAL_CLOSE = "primary.portal.messageCenter.modals.adminRoles.close",
    ADMIN_ROLES_MODAL_LABEL_SUPERVISOR = "primary.portal.messageCenter.modals.adminRoles.supervisory.label",
    ADMIN_ROLES_MODAL_CONTENT_SUPERVISORY = "primary.portal.messageCenter.modals.adminRoles.supervisory.content",
    ADMIN_ROLES_MODAL_LABEL_PRIMARY = "primary.portal.messageCenter.modals.adminRoles.primary.label",
    ADMIN_ROLES_MODAL_CONTENT_PRIMARY = "primary.portal.messageCenter.modals.adminRoles.primary.content",
    ADMIN_ROLES_MODAL_LABEL_STANDARD = "primary.portal.messageCenter.modals.adminRoles.standard.label",
    ADMIN_ROLES_MODAL_CONTENT_STANDARD = "primary.portal.messageCenter.modals.adminRoles.standard.content",
    ASSIGN_ADMIN_MODAL_LABEL_ADMIN_ARIA = "primary.portal.messageCenter.modals.assignAdmin.label-admin.aria",
    ASSIGN_ADMIN_MODAL_HEADER_UPDATE = "primary.portal.messageCenter.modals.assignAdmin.update.header",
    ASSIGN_ADMIN_MODAL_HEADER_SAVE = "primary.portal.messageCenter.modals.assignAdmin.save.header",
    ASSIGN_ADMIN_MODAL_BUTTON_SAVE = "primary.portal.messageCenter.modals.assignAdmin.save.button",
    ASSIGN_ADMIN_MODAL_LABEL_ADMIN = "primary.portal.messageCenter.modals.assignAdmin.label-admin",
    CANCEL_COMPOSE_MODAL_HEADER = "primary.portal.messageCenter.modals.cancelCompose.header",
    CANCEL_COMPOSE_MODAL_BUTTON = "primary.portal.messageCenter.modals.cancelCompose.button",
    CANCEL_COMPOSE_MODAL_CONTENT = "primary.portal.messageCenter.modals.cancelCompose.content",
    CATEGORY_MODAL_HEADER = "primary.portal.messageCenter.modals.category.header",
    CATEGORY_MODAL_BUTTON = "primary.portal.messageCenter.modals.category.button",
    CATEGORY_MODAL_LABEL = "primary.portal.messageCenter.modals.category.label",
    COMMENT_MODAL_HEADER_UPDATE = "primary.portal.messageCenter.modals.comment.update.header",
    COMMENT_MODAL_HEADER_SAVE = "primary.portal.messageCenter.modals.comment.save.header",
    COMMENT_MODAL_CONTENT = "primary.portal.messageCenter.modals.comment.content",
    COMMENT_MODAL_LABEL_COMMENT = "primary.portal.messageCenter.modals.comment.label",
    COMMENT_MODAL_COMMENT_ERROR = "primary.portal.messageCenter.modals.comment.error",
    DELETE_ADMIN_MODAL_HEADER = "primary.portal.messageCenter.modals.deleteAdmin.header",
    DELETE_ADMIN_MODAL_BUTTON = "primary.portal.messageCenter.modals.deleteAdmin.button",
    DELETE_CATEGORY_HEADER = "primary.portal.messageCenter.modals.deleteCategory.header",
    DELETE_CATEGORY_BUTTON = "primary.portal.messageCenter.modals.deleteCategory.button",
    DELETE_COMMENT_HEADER = "primary.portal.messageCenter.modals.deleteComment.header",
    DELETE_COMMENT_BUTTON = "primary.portal.messageCenter.modals.deleteComment.button",
    DELETE_MESSAGE_HEADER = "primary.portal.messageCenter.modals.deleteMessage.header",
    DELETE_MESSAGE_BUTTON = "primary.portal.messageCenter.modals.deleteMessage.button",
    DELETE_MESSAGE_CONTENT = "primary.portal.messageCenter.modals.deleteMessage.content",
    STATUS_MODAL_HEADER = "primary.portal.messageCenter.modals.status.header",
    STATUS_MODAL_BUTTON = "primary.portal.messageCenter.modals.status.button",
    STATUS_MODAL_LABEL = "primary.portal.messageCenter.modals.status.label",
    ADMIN_SETTINGS_HEADER = "primary.portal.messageCenter.admins.header",
    ADMIN_SETTINGS_CONTENT = "primary.portal.messageCenter.admins.content",
    ADMIN_SETTINGS_SHOW_ADMIN_ROLES = "primary.portal.messageCenter.admins.showAdminRoles",
    ADMIN_SETTINGS_SUPERVISOR = "primary.portal.messageCenter.admins.assignments.supervisor",
    ADMIN_SETTINGS_SAVE = "primary.portal.messageCenter.admins.save",
    CATEGORY_ADMIN_ASSIGNMENT_HEADER = "primary.portal.messageCenter.admins.assignment.header",
    CATEGORY_ADMIN_ASSIGNMENT_LABEL_PRIMARY = "primary.portal.messageCenter.admins.assignments.label.primary",
    CATEGORY_ADMIN_ASSIGNMENT_BUTTON_ADD_STANDARD = "primary.portal.messageCenter.admins.assignments.addStandard",
    CATEGORY_ADMIN_ASSIGNMENT_LABEL_ARIA = "primary.portal.messageCenter.admins.assignments.label.primary.aria",
    CATEGORY_ADMIN_ASSIGNMENT_TOOLTIP = "primary.portal.messageCenter.admins.assignments.cannotRemove.tooltip",
    CATEGORY_ADMIN_ASSIGNMENT_ROW_LABEL = "primary.portal.messageCenter.admins.assignments.label.standardAdmin",
    CATEGORY_ADMIN_ASSIGNMENT_ROW_PROMOTE = "primary.portal.messageCenter.admins.assignments.promotePrimary",
    CATEGORY_ADMIN_ASSIGNMENT_ROW_REMOVE = "primary.portal.messageCenter.admins.assignments.removeStandard",
    CATEGORY_ADMIN_ASSIGNMENT_ROW_ARIA = "primary.portal.messageCenter.admins.assignments.label.standardAdmin.aria",
    CATEGORY_SETTINGS_HEADER = "primary.portal.messageCenter.categories.header",
    CATEGORY_SETTINGS_CONTENT = "primary.portal.messageCenter.categories.content",
    CATEGORY_SETTINGS_LABEL_CATEGORY_NAME = "primary.portal.messageCenter.label.categoryName",
    CATEGORY_SETTINGS_LABEL_CONVERSATIONS = "primary.portal.messageCenter.categories.labelDesc.conversations",
    CATEGORY_SETTINGS_LABEL_UNRESOLVED = "primary.portal.messageCenter.categories.labelDesc.unresolved",
    CATEGORY_SETTINGS_LABEL_REMOVE = "primary.portal.messageCenter.categories.labelDesc.remove",
    CATEGORY_SETTINGS_NO_CONVERSATIONS = "primary.portal.messageCenter.categories.noConversations",
    CATEGORY_SETTINGS_CATEGORY_REMOVE = "primary.portal.messageCenter.categories.remove",
    CATEGORY_SETTINGS_ADD_CATEGORY = "primary.portal.messageCenter.categories.addCategory",
    CATEGORY_SETTINGS_SAVE = "primary.portal.messageCenter.categories.save",
    CATEGORY_SETTINGS_TOOLTIP = "primary.portal.messageCenter.categories.labelDesc.remove.toolTip",
    CATEGORY_UPDATE_ROW_LABEL_CATEGORY_NAME = "primary.portal.messageCenter.categories.label.categoryName",
    CATEGORY_UPDATE_ROW_LABEL_CATEGORY_REMOVE = "primary.portal.messageCenter.categories.categoryName.remove",
    INBOX_CONTAINER_HEADER = "primary.portal.messageCenter.header",
    INBOX_CONTAINER_LABEL_SEARCH_BAR = "primary.portal.messageCenter.messages.searchBar.label",
    INBOX_CONTAINER_HINT_SEARCH_BAR = "primary.portal.messageCenter.messages.searchBar.hint",
    INBOX_CONTAINER_TABLE_HEADER_FROM = "primary.portal.messageCenter.messages.tableHeader.from",
    INBOX_CONTAINER_TABLE_HEADER_SUBJECT = "primary.portal.messageCenter.messages.tableHeader.subject",
    INBOX_CONTAINER_TABLE_HEADER_CATEGORY = "primary.portal.messageCenter.messages.tableHeader.category",
    INBOX_CONTAINER_TABLE_HEADER_ASSIGNED_TO = "primary.portal.messageCenter.messages.tableHeader.assignedTo",
    INBOX_CONTAINER_TABLE_HEADER_DATE_RECIEVED = "primary.portal.messageCenter.messages.tableHeader.dateRecieved",
    INBOX_CONTAINER_TABLE_HEADER_MANAGE = "primary.portal.messageCenter.messages.tableHeader.manage",
    INBOX_CONTAINER_MENU_CHANGE_STATUS = "primary.portal.messageCenter.messages.tableMenu.changeStatus",
    INBOX_CONTAINER_MENU_CHANGE_CATEGORY = "primary.portal.messageCenter.messages.tableMenu.changeCategory",
    INBOX_CONTAINER_MENU_MANAGE_ADMIN = "primary.portal.messageCenter.messages.tableMenu.manageAdmin",
    INBOX_CONTAINER_MENU_DELETE_THREAD = "primary.portal.messageCenter.messages.tableMenu.deleteThread",
    INBOX_CONTAINER_ZERO_STATE = "primary.portal.messageCenter.messages.zeroState",
    INBOX_CONTAINER_TAB_INBOX = "primary.portal.messageCenter.messages.tabs.inbox",
    INBOX_CONTAINER_TAB_SENT = "primary.portal.messageCenter.messages.tabs.sent",
    INBOX_CONTAINER_TAB_TRASH = "primary.portal.messageCenter.messages.tabs.trash",
    INBOX_CONTAINER_FILTER_STATUS = "primary.portal.messageCenter.messages.tableFilter.status",
    INBOX_CONTAINER_FILTER_CATEGORY = "primary.portal.messageCenter.messages.tableFilter.category",
    INBOX_CONTAINER_FILTER_ASSIGNED_TO_UNASSIGNED = "primary.portal.messageCenter.messages.tableFilter.assignedTo.unassigned",
    INBOX_CONTAINER_FILTER_ASSIGNED_TO_ME = "primary.portal.messageCenter.messages.tableFilter.assignedTo.assignToMe",
    INBOX_CONTAINER_FILTER_ASSIGNED_TO = "primary.portal.messageCenter.messages.tableFilter.assignedTo",
    SETTINGS_CONTAINER_HEADER = "primary.portal.messageCenter.header",
    SETTINGS_CONTAINER_TAB_CATEGORIES = "primary.portal.messageCenter.settings.tabs.categories",
    SETTINGS_CONTAINER_TAB_ADMINS = "primary.portal.messageCenter.settings.tabs.admins",
    TARGET_UNIT_PIPE_MULTIPLE = "primary.portal.general.dereferenceTargetPipe.multipleRecipients",
}

export enum MicroSiteLanguage {
    ACCOUNT_LANDING_PAGE = "primary.portal.primaryNav.accountLandingPages",
}
export enum ArgusLanguage {
    SELECT_ONE_NON_PLHSO_PRODUCT = "secondary.portal.benefitsOffering.1NonPLHSO",
}

export enum BrandingLanguage {
    NO_BROKERAGE_TIED_ERROR = "primary.portal.branding.noBrokerage.upload_failed",
    BRANDING_UPLOAD_FAILED_ERROR = "primary.portal.branding.upload_failed",
}

export enum DependentAddressUpdateModalLanguage {
    CLOSE = "primary.portal.dependent.address.close",
    BUTTON_SKIP = "primary.portal.dependent.address.button.skip",
    BUTTON_UPDATE = "primary.portal.dependent.address.button.update",
    HEADER = "primary.portal.dependent.address.header",
    CONTENT = "primary.portal.dependent.address.content",
    SELECTION_REQUIRED = "primary.portal.dependent.address.selectionRequired",
    DEPENDENT_FETCH_ERROR = "primary.portal.dependent.address.apiError",
}
