export enum MissingInfoType {
    ADDRESS = "ADDRESS",
    AGE = "AGE",
    BIRTH_DATE = "BIRTH_DATE",
    CARRIER_APPOINTMENT = "CARRIER_APPOINTMENT",
    ELIGIBLE_EMPLOYEES = "ELIGIBLE_EMPLOYEES",
    GENDER = "GENDER",
    OCCUPATION_CLASS = "OCCUPATION_CLASS",
    SALARY = "SALARY",
    SIC_CODE = "SIC_CODE",
    SPOUSE_AGE = "SPOUSE_AGE",
    WORK_ZIP_STATE = "WORK_ZIP_STATE",
}
