export enum Operation {
    EQUALS = "EQUALS",
    NOT_EQUALS = "NOT_EQUALS",
    LESS_THAN = "LESS_THAN",
    GREATER_THAN = "GREATER_THAN",
    LESS_THAN_OR_EQUALS = "LESS_THAN_OR_EQUALS",
    GREATER_THAN_OR_EQUALS = "GREATER_THAN_OR_EQUALS",
}
