export enum PagePrivacy {
    ACCOUNT_CONTACTS = "AccountContactPage",
    ACCOUNT_ADMINISTRATOR = "AccountAdministratorsPage",
    ACCOUNT_ENROLLMENT_OPTIONS = "AccountThirdPartyEnrollmentOption",
    ACCOUNT_STRUCTURE = "AccountRuleStructurePage",
    ACCOUNT_CARRIERS = "ImportAflacGroup_Under_Accountcarriers",
    ACCOUNT_RESOURCES = "AccountResourcesPage",
    ACCOUNT_RULES = "AccountRulesPage",
    BENEFIT_OFFERING_MANAGE_PRODUCT = "BenefitOfferingProductPage",
    BENEFIT_OFFERING_MANAGE_SETTINGS = "BenefitOfferingSettingsPage",
    BENEFIT_OFFERING_EMPLOYER_CONTRIBUTIONS = "BenefitOfferingEmployerContributionsPage",
    COMMISSIONS_SPLIT = "CommissionsSplitPage",
    BENEFIT_OFFERING_PROPOSAL = "Proposalpage",
    CASE_BUILDER = "CaseBuilderPage",
}
