export enum PartnerAccountType {
    PAYROLL = "PAYROLL",
    NONPAYROLL = "NONPAYROLL",
    UNION = "UNION",
    ASSOCIATION = "ASSOCIATION",
    PAYROLLDIRECTBILL = "PAYROLLDIRECTBILL",
    DIRECT = "DIRECT",
    PARTNERSHIP = "PARTNERSHIP",
}
