export enum RequiredSetup {
    PLAN_YEAR = "PLAN_YEAR",
    PRICING = "PRICING",
    CARRIER_FORM = "CARRIER_FORM",
    HR_APPROVAL = "HR_APPROVAL",
    BINDER = "BINDER",
    ENROLLMENT = "ENROLLMENT",
    CARRIER_APPROVAL = "CARRIER_APPROVAL",
    HQ_APPROVAL = "HQ_APPROVAL",
    NOT_SUBMITTED = "NOT_SUBMITTED",
}
