export enum ROLE {
    PRIMARY_PRODUCER = "PRIMARY_PRODUCER",
    WRITING_PRODUCER = "WRITING_PRODUCER",
    ENROLLER = "ENROLLER",
    HQ_EXCHANGE_TEAM_SUPPORT = "HQ EXCHANGE TEAM SUPPORT",
    MANAGING_PRODUCER = "MANAGING PRODUCER",
    NONAUTHORIZED_PRODUCER = "NONAUTHORIZED_PRODUCER",
    CASE_BUILDER = "CASE BUILDER",
}
