export enum SettingsDropdownName {
    METHOD = "method",
    LOCATION = "location",
    DATES = "dates",
    OCCUPATION = "occupation",
    MORE = "more",
    APPLICANT = "applicant",
    SPOUSE = "spouse",
    BENEFIT_AMOUNT = "benefit",
    ELIMINATION_PERIOD = "elimination",
    RIDERS = "riders",
    DEPENDENT_AGE = "dependent",
    STATE = "state",
    CHANNEL = "channel",
    PAYMENT_FREQUENCY = "payment",
    JOB_CLASS = "job",
    AGE = "age",
    AGE_BANDS = "age-bands",
    TOBACCO = "tobacco",
    NON_TOBACCO = "non-tobacco",
    GENDER = "gender",
}
