export enum StatusType {
    PENDING = "PENDING",
    PENDING_HR_APPROVAL = "PENDING_HR_APPROVAL",
    PENDING_AFLAC_APPROVAL = "PENDING_AFLAC_APPROVAL",
    APPROVED = "APPROVED",
    DENIED = "DENIED",
    INPROGRESS = "IN_PROGRESS",
    SUBMITTED = "SUBMITTED",
    NOT_SUBMITTED = "NOT_SUBMITTED",
    DECLINED = "DECLINED",
    SUBMITTED_TO_HR = "SUBMITTED_TO_HR",
    SUBMITTED_TO_HQ = "SUBMITTED_TO_HQ",
    AUTO_APPROVED = "AUTO_APPROVED",
}
