export enum CarrierStatus {
    ACTIVE = "ACTIVE",
    LAPSED = "LAPSED",
    PENDING = "PENDING",
    TERMINATED = "TERMINATED",
    WITHDRAWN = "WITHDRAWN",
    POSTPONED = "POSTPONED",
    CLOSE_INCOMPLETE = "CLOSE_INCOMPLETE",
    DECLINED = "DECLINED",
    CANCELLED = "CANCELLED",
}
