export enum coverageStartFunction {
    DAY_AFTER = "DAY_AFTER",
    NEXT_FIRST_OF_MONTHNEXT_FIRST_OF_MONTH = "NEXT_FIRST_OF_MONTH",
    NEXT_FIRST_OR_FIFTEENTH_OF_MONTH = "NEXT_FIRST_OR_FIFTEENTH_OF_MONTH",
}
