export enum QLEEndPlanRequestStatus {
    COVERAGE_CANCELLED = "COVERAGE_CANCELLED",
    COVERAGE_CANCELLATION_REQUEST_SUBMITTED = "COVERAGE_CANCELLATION_REQUEST_SUBMITTED",
    PENDING_HR_APPROVAL = "PENDING_HR_APPROVAL",
}
