export enum StepTitle {
    TOBACCO = "Tobacco Use",
    SPOUSE_TOBACCO = "Spouse Tobacco Use",
    SIGN = "Sign Your Application Forms",
    BENEFICIARY = "Beneficiary",
    COVERAGE_OPTIONS = "Coverage Options",
    RIDERS = "Riders",
    UNDERWRITING = "Underwriting Questions",
    ELIGIBILITY = "Eligibility Questions",
    CONVERSION = "Conversion",
    PLANINFORMATION = "Plan Information",
    REQUIREDFORMS = "Required Forms\r\n",
    APPLICANTS = "Applicant's Statements and Agreements",
    BENEFICIARIES = "Beneficiaries",
    REQUIREDFORMS1 = "Required Forms",
    PAYMENTOPTION = "Payment Option",
    PAYMENTLCOPTION = "Payment option",
    REQUIREDFORMS2 = "Required Forms\r\n\r\n",
    ARBITRATIONAGREEMENT = "Arbitration Agreement",
    SEND_VERIFICATION = "Send Verification Code",
    PAYLOGIX_PAYMENT = "Paylogix",
}
