export enum ExceptionType {
    ALLOW_WITHDRAWN_PLAN = "ALLOW_WITHDRAWN_PLAN",
    ALLOWED_ENROLLMENT_EXCEPTIONS = "ALLOWED_ENROLLMENT_EXCEPTIONS",
    VAS_MAX_EMPLOYEE = "VAS_MAX_EMPLOYEE",
    VAS_YEAR_ONE_PRODUCT_ADD = "VAS_YEAR_ONE_PRODUCT_ADD",
    VAS_RENEWAL_YEAR_PRODUCT_ADD = "VAS_RENEWAL_YEAR_PRODUCT_ADD",
    VAS_MULTIPLE_AFLAC_FUNDED = "VAS_MULTIPLE_AFLAC_FUNDED",
    AG_SPOUSE_BENEFIT_PERCENTAGE = "AG_SPOUSE_BENEFIT_PERCENTAGE",
    ALLOWED_DISABILITY_ENROLLMENT = "ALLOWED_DISABILITY_ENROLLMENT",
}
