export enum EmpSidenavContent {
    EMPLOYEES = "primary.portal.sideNavBar.employees",
    PRIMARY = "primary.portal.sideNavBar.primary",
    DEPENDENTS = "primary.portal.sideNavBar.dependents",
    BENEFICIARIES = "primary.portal.sideNavBar.beneficiaries",
    COMPLETED_FORMS = "primary.portal.sideNavBar.completedForms",
    SUMMARY = "primary.portal.sideNavBar.summary",
    BENEFIT_DOLLARS = "primary.portal.sideNavBar.benefitDollars",
    LIFE_EVENTS = "primary.portal.sideNavBar.lifeEvents",
    PENDING_ENROLLMENTS = "primary.portal.sideNavBar.pendingEnrollments",
    POLICY_CHANGE_REQUESTS = "primary.portal.sideNavBar.policyChangeRequests",
    DOCUMENTS_AND_NOTES = "primary.portal.sideNavBar.documentsAndNotes",
    ACTIVITIES = "primary.portal.sideNavBar.activities",
    PROFILE_CHANGES = "primary.portal.sideNavBar.profileChanges",
    ENROLLMENTS = "primary.portal.sideNavBar.enrollments",
    SHOP = "primary.portal.sideNavBar.shop",
    LIFE_EVENT_ENROLLMENT = "primary.portal.sideNavBar.lifeEventEnrollment",
    OPEN_ENROLLMENT = "primary.portal.sideNavBar.openEnrollment",
    REPORTS = "primary.portal.sideNavBar.reports",
    COMMISSIONS = "primary.portal.sideNavBar.commissions",
    CUSTOMERS = "primary.portal.sideNavBar.customers",
    SCHEDULE_AND_SEND = "primary.portal.sideNavBar.scheduleAndSend",
    PERSONAL_INFO = "primary.portal.sideNavBar.personalInfo",
    EMAIL = "primary.portal.sideNavBar.emailAndTexts",
}
