export enum EnrollmentReportStatus {
    APPROVED = "APPROVED",
    PENDING = "PENDING",
    PENDING_PDA = "PENDING_PDA",
    PENDING_EEA = "PENDING_EEA",
    PENDING_OTHER_REASONS = "PENDING_OTHER_REASONS",
    PENDING_SIGNATURE = "PENDING_SIGNATURE",
}
