export enum SystemFlowCode {
    HEADSET_PAYROLL = "HEADSET_PAYROLL",
    HEADSET_DIRECT = "HEADSET_DIRECT",
    HEADSET_PROSPECT = "HEADSET_PROSPECT",
    CALL_CENTER_DIRECT = "CALLCENTER_DIRECT",
    CALL_CENTER_PAYROLL = "CALLCENTER_PAYROLL",
    VIRTUALF2F_PAYROLL = "VIRTUALF2F_PAYROLL",
}
