/**
 * @deprecated AppSettings is no longer being updated, and its values might be outdated
 *
 * Instead of updating or using,
 * please find values elsewhere / copy values from this constant and create a new const in constants lib (or enum, type, etc)
 */
export const AppSettings = {
    ENGLISH: "ENGLISH",
    SPANISH: "SPANISH",
    pageSizeOptions: [15, 25, 50],
    errorLogPageSizeOptions: [10, 20, 30, 40, 50],
    historyPageSizeOptions: [10, 20, 50, 100],
    HEIGHTINFEET: [1, 2, 3, 4, 5, 6, 7],
    HEIGHTININCH: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    SPOUSE_MIN_AGE: 18,
    CHILD_MAX_AGE: 26,
    DATE_FORMAT: "yyyy-MM-dd",
    DATE_FORMAT_MM_DD_YYYY: "MM/dd/yyyy",
    DATE_FORMAT_D: "d",
    DATE_MONTH_FORMAT: "MMMM",
    DATE_FORMAT_MM_YYYY: "MM/YYYY",
    DATE_FORMAT_YYYY_MM_DD: "yyyy-MM-dd",
    MONTH_YEAR_FORMAT: "MMM YYYY",
    MONTH_DATE_FORMAT: "MMMM dd",
    MONTH_DATE_FORMAT_MM_DD: "MM/dd",
    YEAR_FORMAT: "yyyy",
    DATE_A11_LABEL: "LL",
    DATE_TIME_FORMAT: "MM/dd/yyyy hh:mm:ss",
    DATE_TIME_FORMAT_HR_MN: "MM/dd/yyyy hh:mm a",
    TIME_FORMAT_HR_MN: "hh:mm a",
    DATE_MASK_FORMAT: "09/09/0000",
    PHONE_NUMBER_FORMAT: "000-000-0000",
    DATE_FORMAT_YYYY_MM_DD_1: "YYYY-MM-DD",
    DATE_FORMAT_YYYY_MM: "YYYY-MM",
    DATE_FORMAT_MM_DD_YYYY_1: "MM/DD/YYYY",
    DATE_FORMAT_MMMM_YYYY: "MMMM YYYY",
    API_RESP_200: 200,
    API_RESP_201: 201,
    API_RESP_202: 202,
    API_RESP_204: 204,
    API_RESP_300: 300,
    API_RESP_301: 301,
    API_RESP_302: 302,
    API_RESP_303: 303,
    API_RESP_304: 304,
    API_RESP_307: 307,
    API_RESP_400: 400,
    API_RESP_401: 401,
    API_RESP_403: 403,
    API_RESP_404: 404,
    API_RESP_405: 405,
    API_RESP_406: 406,
    API_RESP_408: 408,
    API_RESP_409: 409,
    API_RESP_412: 412,
    API_RESP_413: 413,
    API_RESP_415: 415,
    API_RESP_500: 500,
    API_RESP_501: 501,
    API_RESP_503: 503,
    API_RESP_504: 504,
    API_RESP_HEADER_LOCATION: "location",
    AFLAC_CARRIER: "Aflac",
    AFLAC_GROUP_CARRIER: "Aflac Group",
    VALUE_ADDED_SERVICES: "Value Added Services (VAS)",
    VAS_EMP: "VAS_EMP_FUNDED",
    VAS_EMP_FUNDED: "Employee- & employer-funded",
    HQ: "HQ",
    VAS_HQ_FUNDED: "HQ-funded",
    VAS: "VAS",
    GROUP: "GROUP",
    INDIVIDUAL: "INDIVIDUAL",
    MAX_LENGTH_100: 100,
    MEMBER_HEIGHTINFEET: [0, 1, 2, 3, 4, 5, 6, 7],
    MEMBER_HEIGHTININCH: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    PORTAL_PRODUCER: "PRODUCER",
    PORTAL_ADMIN: "ADMIN",
    PORTAL_MEMBER: "MEMBER",
    PORTAL_PUBLIC: "public",
    DISPLAY_GROUP: "Group",
    DISPLAY_INDIVIDUAL: "Individual",
    MAX_LENGTH_20: 20,
    AND: "AND",
    OR: "OR",
    MISSINGPARAMETER: "missingParameter",
    BADPARAMETER: "badParameter",
    DUPLICATE: "duplicate",
    PRETAX: "PRETAX",
    SELFDUPLICATE: "selfDuplicate",
    FILE_SIZE_4MB: 4242880,
    FILE_SIZE_8MB: 9242880,
    MAX_LENGTH_200: 200,
    DATE_TIME: "T00:00:00",
    DEMOGRAPHICS_CONTACT_TIME: ["MORNING", "AFTERNOON", "EVENING"],
    CALENDAR_MAX_LEN: 10,
    UNKNOWN: "UNKNOWN",
    MAX_LENGTH_5: 5,
    DOC_LENGTH: 24,
    DOC_LENGTH_FIRST_N_CHARS: 16,
    DOC_LENGTH_LAST_N_CHARS: 8,
    DEDUCTION_DATE_PER_PERIOD: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
    MAX_LENGTH_8: 8,
    PAYROLL_ACCOUNT: "PAYROLL",
    NON_PAYROLL_ACCOUNT: "NONPAYROLL",
    NON_PAYROLL_ACH_ACCOUNT: "NONPAYROLL_ACH",
    ASSOCIATION_ACCOUNT: "ASSOCIATION",
    ASSOCIATION_ACH_ACCOUNT: "ASSOCIATION_ACH",
    HEIGHT: "Height",
    WEIGHT: "Weight",
    DRIVERS_LICENSE_NO: "Driver's License Number",
    DRIVERS_LICENSE_STATE: "Driver's License State",
    SSN: "Social Security Number",
    PREFERRED_CONTACT_TIME: "Preferred Contact Time",
    EMAIL: "Email Address",
    ADDRESS: "address",
    EMPLOYEE_ID: "Employee Id",
    SALARY: "Salary",
    HOURSPERWEEK: "Hours per week",
    YES: "yes",
    REPLACE_GLOSSARY: "{glossary}",
    REPLACE_SALARY: "<u><strong>salary</strong></u>",
    BANK_DRAFT: "BANK_ACCOUNT",
    CREDIT_CARD: "CREDIT_CARD",
    NO: "no",
    CONTACT_LATER: "contact_later",
    INVALID_FILE_EXETENSIONS_FOR_DOCUMENT: ["bat", "exe", "dll", "sh", "bmp", "avi", "mov", "gif", "ini", "jpg", "sys", "wav", "mp3"],
    INVALID_FILE_EXETENSIONS_FOR_PCR_DOCUMENT: ["bat", "exe", "dll", "sh", "bmp", "avi", "mov", "gif", "ini", "sys", "wav", "mp3"],
    DISABILITY_DOWNGRADE: "DISABILITY_DOWNGRADE",
    CANCEL: "cancel",
    CONTINUE: "continue",
    MAX_LENGTH_16: 16,
    MAX_LENGTH_24: 24,
    MAX_LENGTH_9: 9,
    MAX_LENGTH_10: 10,
    PAGE_SIZE_1000: 1000,
    API_UNSUPPORTED_MEDIA_TYPE: "unsupportedMediaType",
    COMPLETE: "COMPLETE",
    PROCESSING: "PROCESSING",
    VIRUS_SCAN_FAILED: "VIRUS_SCAN_FAILED",
    INVALID_DATE: "Invalid Date",
    HUNDRED: 100,
    NINETY_SEVEN: 97,
    NINETY_EIGHT: 98,
    NINETY_NINE: 99,
    START_DATE_OFFSET_DAYS: 364,
    END_DATE_OFFSET_YEARS: 2,
    ONE: 1,
    TWO: 2,
    COUNTRY_US: "US",
    PHONE_NUM_MAX_LENGTH: 12,
    SSN_MIN_LENGTH: 9,
    MAX_CHARACTERS: 5000,
    MIN_AMOUNT: 0.01,
    PUERTO_RICO: "Puerto Rico",
    PR: "PR",
    WAIVED: "waived",
    FACE_TO_FACE: "FACE_TO_FACE",
    HEADSET: "HEADSET",
    LIFE: "Life",
    MONTHNAMES: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    COMPLETED: "COMPLETED",
    ROLE_ID_12: 12,
    VIRTUAL_CONTACT_CENTER: 11,
    NOT_FOUND: "notFound",
    HISTORY_MATCH: "historyMatch",
    APPFLOW_ACTION: "appFlow",
    ANNUAL: "Annually",
    QUERY_PARAM_ACCOUNT_ID: "accountId",
    PRIMARY: "Primary",
    BENEFICIARY_PERCENTAGE: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    RELIANCE_CARRIER: "Reliance Standard Life Insurance Company",
    VISION: "30",
    DENTAL: "13",
    OTHER_ACCIDENT: "Other accident or Health Plan(s) under Section 106 of the Internal Revenue Service code",
    SINGLE: "SINGLE",
    MULTIPLE: "MULTIPLE",
    ADDRESS_BOTH_OPTION: "bothOption",
    ADDRESS_SINGLE_OPTION: "singleOption",
    IDLE_TIME: 1740,
    UNPLUGGED_CONFIG: "general.feature.disable.for_unplugged",
    TEMPORARY_ADDRESS: "providedAddress",
    SUGGESTED_ADDRESS: "suggestedAddress",
    BREAKPOINT_SIZES: {
        XS: "XS",
        SM: "SM",
        MD: "MD",
        LG: "LG",
        XL: "XL",
    },
    TRANSFORM_VALUE: "00/00/0000",
    PEND_DATE_MAX_OFFSET: 35,
    PLAN: "PLAN",
    PLANS: "plans",
    CARRIER_FORMS: "CARRIER_FORMS",
    INVALIDSTATE: "invalidState",
    PHONE_FORMAT: "PHONE",
    ENROLLED: "Enrolled",
    JUVENILE_CHILD_MAX_AGE: 17,
    CARRIER_APPROVAL: "CARRIER_APPROVAL",
    PRICING: "PRICING",
    HR_APPROVAL: "HR_APPROVAL",
    GROUP_RATED: "GROUP_RATED",
    COMPANY_NAME_MIN_LENGTH: 3,
    PARTNER_ID: "2",
    RESOURCE_ACKNOWLEDGEMENT: "RESOURCE_ACKNOWLEDGEMENT",
    APPROVEDSTATUS: "APPROVED",
    REJECTEDSTATUS: "REJECTED",
    APPROVESTATUS: "APPROVE",
    REJECTSTATUS: "REJECT",
    JUVENILE: "Juvenile",
    DIRECT: "direct",
    PAYROLL: "payroll",
    CALL_CENTER: "CALL_CENTER",
    specificDate: "specificDate",
    dateRange: "dateRange",
    IMPORT_ACCOUNT_INLINE_ERROR_CODE_PATTERN: /400|404|403|duplicate/g,
    NumberValidationRegex: "[0-9]",
    BUILDING_BENEFIT_RIDER: 789,
    DEPENDENT_CHILD_RIDER: 790,
    IS_EMPLOYEE_ID_REQUIRED: "is_employee_id_required",
    IS_DEPARTMENT_ID_REQUIRED: "is_department_number_required",
    RELIANCE_CUSTOM_FORM_ID: 74,
    RELIANCE_CUSTOM_FORM_STEP_2_PAGE1_INDEX: 4,
    RELIANCE_CUSTOM_FORM_NUMBER_OF_STEPS: 2,
    TRUE: "true",
    FALSE: "false",
    NULL: null,
    AFLAC_PARTNER_ID: 2,
    NOTAUTHORIZED: "notAuthorized",
    SSOREQUIRED: "ssoRequired",
    ACTUAL_SALARY_TYPE: "ACTUAL",
    WEEKS_IN_YEAR: 52,
    RPM_NAVIGATION_URL: "https://myrpm.aflac.com/Home.aspx",
    PEO: "PEO",
    STANDARD: "STANDARD",
    CONFLICT: "conflict",
    LOCKED: "locked",
    DEPENDENTAGEOPTIONS: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    // API team is still working on config hence it is hard coded, will come from config later
    JUVENILETERMLIFE: 65,
    JUVENILEWHOLELIFE: 67,
    CARD_NUMBER_MIN_LENGTH: 15,
    AFLAC_PASS_CARRIERID: 64,
    GOHEALTH_CARRIERID: 25,
    NOT_ELIGIBLE: "NOT_ELIGIBLE",
    INACTIVE: "INACTIVE",
    INVALID_APPLICATION_STATE: "invalidApplicationState",
    TPI: "tpi",
};
