export const ARGUS_CONFIG_API_RESPONSE_INDEX = {
    DENTAL_TIER_ONE_ALL_STATES_PLANS_INDEX: 0,
    DENTAL_TIER_TWO_ALL_STATES_PLANS_INDEX: 1,
    DENTAL_TIER_ONE_FL_STATE_PLANS_INDEX: 2,
    DENTAL_TIER_TWO_FL_STATE_PLANS_INDEX: 3,
    DENTAL_TIER_ONE_PPO_PLANS_INDEX: 4,
    DENTAL_TIER_ONE_MAC_PLANS_INDEX: 5,
    DENTAL_TIER_TWO_PPO_PLANS_INDEX: 6,
    DENTAL_TIER_TWO_MAC_PLANS_INDEX: 7,
    DENTAL_TIER_ONE_PPO_ER_PLANS_INDEX: 8,
    DENTAL_TIER_ONE_MAC_ER_PLANS_INDEX: 9,
    DENTAL_TIER_TWO_PPO_ER_PLANS_INDEX: 10,
    DENTAL_TIER_TWO_MAC_ER_PLANS_INDEX: 11,
};
export const ARGUS_CONFIG_API_RESPONSE_VISION_INDEX = {
    VISION_TIER_ONE_EMPLOYEE_PAID: 0,
    VISION_TIER_TWO_EMPLOYEE_PAID: 1,
    VISION_TIER_ONE_EMPLOYER_PAID: 2,
    VISION_TIER_TWO_EMPLOYER_PAID: 3,
};

export const ARGUS_CONFIG_API_RESPONSE_FLORIDA_INDEX = {
    DENTAL_TIER_ONE_PPO_PLANS_INDEX: 0,
    DENTAL_TIER_ONE_MAC_PLANS_INDEX: 1,
    DENTAL_TIER_TWO_PPO_PLANS_INDEX: 2,
    DENTAL_TIER_TWO_MAC_PLANS_INDEX: 3,
    DENTAL_TIER_ONE_PPO_ER_PLANS_INDEX: 4,
    DENTAL_TIER_ONE_MAC_ER_PLANS_INDEX: 5,
    DENTAL_TIER_TWO_PPO_ER_PLANS_INDEX: 6,
    DENTAL_TIER_TWO_MAC_ER_PLANS_INDEX: 7,
    DENTAL_DHMO_PLANS_INDEX: 8,
};
