export const EnrollmentConstants = {
    productIds: {
        MEDICAL: [4],
        HSAFSA: [39, 48, 53, 70, 69, 77],
        FSA: [39, 53, 69, 77],
        HSA: [48, 70],
        Juvenile: [65, 67],
        AFLAC_PASS: [60],
        LIFE: [28, 29],
    },
    dependentRelation: {
        SPOUSE: 1,
        CHILD: 2,
    },
    coverageId: {
        INDIVIDUAL: [
            { id: 23, name: "Employee Only" },
            { id: 51, name: "Employee Only" },
            { id: 56, name: "Employee Only" },
            { id: 66, name: "Employee Only" },
            { id: 75, name: "Employee Only" },
            { id: 89, name: "Employee Only" },
            { id: 132, name: "Employee Only" },
            { id: 136, name: "Employee Only $10 copay" },
            { id: 140, name: "Employee Only $25 copay" },
            { id: 160, name: "Employee Only UHC IA" },
            { id: 168, name: "Employee Only" },
            { id: 172, name: "Employee Only" },
            { id: 176, name: "Employee Only" },
            { id: 180, name: "Employee Only" },
            { id: 184, name: "Employee Only" },
            { id: 188, name: "Employee Only" },
            { id: 194, name: "Employee Only Unum CO" },
            { id: 196, name: "Employee Only" },
            { id: 205, name: "Employee Only" },
            { id: 206, name: "Option 1 - Employee Only" },
            { id: 207, name: "Option 2 - Employee Only" },
            { id: 227, name: "Employee Only" },
            { id: 231, name: "Employee Only" },
            { id: 237, name: "Employee Only" },
            { id: 248, name: "Employee Only" },
            { id: 252, name: "Employee Only" },
            { id: 254, name: "Part Time Life - Employee Only" },
            { id: 256, name: "AD&D Employee Only" },
            { id: 263, name: "Employee Only" },
            { id: 269, name: "Employee Only" },
            { id: 280, name: "Employee Only" },
            { id: 290, name: "Employee Only" },
            { id: 312, name: "Employee Only" },
            { id: 325, name: "Employee" },
            { id: 276, name: "Ameritas Vision EE" },
            { id: 3, name: "Individual" },
            { id: 27, name: "Individual" },
            { id: 70, name: "Individual - No Rider" },
            { id: 80, name: "Individual" },
            { id: 81, name: "Individual with Rider" },
            { id: 329, name: "Individual Buy Up" },
            { id: 285, name: "Self" },
            { id: 316, name: "Member only" },
            { id: 1, name: "Enrolled" },
            { id: 258, name: "Enrolled - 100% Weekly Base Pay" },
            { id: 259, name: "Enrolled - 60% Weekly Base Pay" },
            { id: 260, name: "Enrolled - 60% Normal Base Pay" },
        ],
        SPOUSE: [
            { id: 264, name: "Employee + Spouse" },
            { id: 270, name: "Employee + Spouse" },
            { id: 281, name: "Employee & Spouse" },
            { id: 291, name: "Employee + Spouse" },
            { id: 326, name: "Employee + Spouse" },
            { id: 313, name: "Employee + Spouse" },
            { id: 24, name: "Employee + Spouse" },
            { id: 52, name: "Employee + Spouse" },
            { id: 55, name: "Employee + Spouse" },
            { id: 67, name: "Employee + Spouse" },
            { id: 78, name: "Employee + Spouse" },
            { id: 90, name: "Employee + Spouse" },
            { id: 133, name: "Employee + Spouse" },
            { id: 137, name: "Employee + Spouse $10 copay" },
            { id: 141, name: "Employee + Spouse $25 copay" },
            { id: 169, name: "Employee + Spouse" },
            { id: 173, name: "Employee + Spouse" },
            { id: 177, name: "Employee + Spouse" },
            { id: 189, name: "Employee + Spouse" },
            { id: 228, name: "Employee + Spouse" },
            { id: 232, name: "Employee + Spouse" },
            { id: 238, name: "Employee + Spouse" },
            { id: 249, name: "Employee + Spouse" },
            { id: 277, name: "Ameritas Vision EE + Spouse" },
            { id: 330, name: "Named Insured/Spouse Only Buy Up" },
            { id: 4, name: "Named Insured/Spouse Only" },
            { id: 28, name: "Named Insured / Spouse Only" },
            { id: 82, name: "Named Insured / Spouse Only" },
            { id: 83, name: "Named Insured / Spouse Only with Rider" },
            { id: 287, name: "Spouse" },
            { id: 261, name: "Spouse Life" },
            { id: 181, name: "Employee Spouse" },
            { id: 185, name: "Employee Spouse" },
            { id: 197, name: "Employee Spouse" },
            { id: 161, name: "Employee Spouse UHC IA" },
            { id: 195, name: "Employee Spouse Unum CO" },
            { id: 317, name: "Member + 1" },
        ],
        ONE_PARENT_FAMILY: [
            { id: 91, name: "Employee + Children" },
            { id: 25, name: "Employee + Children" },
            { id: 35, name: "Employee + Children" },
            { id: 53, name: "Employee + Children" },
            { id: 68, name: "Employee + Children" },
            { id: 134, name: "Employee + Children" },
            { id: 138, name: "Employee + Children $10 copay" },
            { id: 142, name: "Employee + Children $25 copay" },
            { id: 170, name: "Employee + Children" },
            { id: 174, name: "Employee + Children" },
            { id: 178, name: "Employee + Children" },
            { id: 208, name: "Employee + Children" },
            { id: 229, name: "Employee + Children" },
            { id: 233, name: "Employee + Children" },
            { id: 239, name: "Employee + Children" },
            { id: 250, name: "Employee + Children" },
            { id: 265, name: "Employee + Children" },
            { id: 271, name: "Employee + Children" },
            { id: 282, name: "Employee & Children" },
            { id: 292, name: "Employee + Children" },
            { id: 314, name: "Employee + Children" },
            { id: 327, name: "Employee + Child(ren)" },
            { id: 278, name: "Ameritas Vision - EE + Children" },
            { id: 11, name: "One Parent Family" },
            { id: 29, name: "One Parent Family" },
            { id: 84, name: "One Parent Family" },
            { id: 85, name: "One Parent Family with Rider" },
            { id: 331, name: "One Parent Family Buy Up" },
            { id: 76, name: "1 Parent Family - Employee and Children" },
            { id: 162, name: "Employee Children UHC IA" },
            { id: 198, name: "Employee Children" },
            { id: 182, name: "Employee Children" },
            { id: 186, name: "Employee Children" },
            { id: 284, name: "Child" },
            { id: 262, name: "Child Life" },
            { id: 57, name: "1 Child" },
            { id: 58, name: "2 Children" },
            { id: 59, name: "3 or more Children" },
        ],
        TWO_PARENT_FAMILY: [
            { id: 266, name: "Employee + Family" },
            { id: 272, name: "Employee + Family" },
            { id: 293, name: "Employee + Family" },
            { id: 315, name: "Employee + Family" },
            { id: 26, name: "Employee + Family" },
            { id: 36, name: "Employee + Family" },
            { id: 54, name: "Employee + Family" },
            { id: 69, name: "Employee + Family" },
            { id: 79, name: "Employee + Family" },
            { id: 92, name: "Employee + Family" },
            { id: 135, name: "Employee + Family" },
            { id: 139, name: "Employee + Family $10 copay" },
            { id: 143, name: "Employee + Family $25 copay" },
            { id: 171, name: "Employee + Family" },
            { id: 175, name: "Employee + Family" },
            { id: 179, name: "Employee + Family" },
            { id: 191, name: "Employee + Family" },
            { id: 230, name: "Employee + Family" },
            { id: 234, name: "Employee + Family" },
            { id: 240, name: "Employee + Family" },
            { id: 251, name: "Employee + Family" },
            { id: 253, name: "Employee + Family" },
            { id: 268, name: "Employee & Family" },
            { id: 283, name: "Employee & Family" },
            { id: 279, name: "Ameritas Vision - EE + Family" },
            { id: 328, name: "Employee + Spouse & Children" },
            { id: 319, name: "Two Parent Family" },
            { id: 332, name: "Two Parent Family Buy Up" },
            { id: 12, name: "Two Parent Family" },
            { id: 30, name: "Two Parent Family" },
            { id: 86, name: "Two Parent Family" },
            { id: 87, name: "Two Parent Family with Rider" },
            { id: 65, name: "2 Parent Family - Employee and Spouse/Children" },
            { id: 183, name: "Employee Family" },
            { id: 187, name: "Employee Family" },
            { id: 199, name: "Employee Family" },
            { id: 163, name: "Employee Family UHC IA" },
            { id: 286, name: "Family" },
            { id: 318, name: "Family" },
            { id: 255, name: "Part Time Life - Family" },
            { id: 257, name: "AD&D Family" },
        ],
    },
    hsaCoverage: {
        INDIVIDUAL: "Individual",
        FAMILY: "Family",
    },
    REDIRECT: "REDIRECT",
    PRODUCT_COST_PRECISION: 4,
};

export const PRELIMINARY_NOTICE = "PRELIMINARY_NOTICE";
