export const PaymentInfo = {
    ROUTING_NUMBER_MIN_LENGTH: 9,
    ACCOUNT_NUMBER_MIN_LENGTH: 6,
    ACCOUNT_NUMBER_MAX_LENGTH: 24,
    CARD_NUMBER_MIN_LENGTH: 15,
    CARD_NUMBER_MAX_LENGTH: 16,
    LAST_FOUR_DIGITS_LENGTH: 4,
    AMEX_CARD_NUMBER_MAX_LENGTH: 15,
};
export const STAR = "*";
