export const SidenavRoutes = {
    MPP_PAYROLL: "../../../payroll",
    MAP_ACCOUNTLIST: "/admin/accountList",
    DASHBOARD: "../dashboard",
    ACCOUNT_INFO: "profile/account-info",
    CONTACTS: "profile/contacts",
    DISPLAY_ADMIN_LIST: "assign-admin/display-admin-list",
    ENROLLMENT_OPTIONS: "enrollment-options",
    CASE_BUILDER_ADMINS: "case-builder",
    STRUCTURE: "profile/structure",
    CARRIERS: "profile/carriers",
    RESOURCES: "resources",
    RULES: "profile/rules",
    EXCEPTIONS: "exceptions",
    PROPOSALS: "proposals",
    CHANGE_REQUESTS: "change-requests",
    EMPLOYEES: "employees",
    SCHEDULE_SEND: "business/schedule-send",
    PENDING_ENROLLMENTS: "business/pending-enrollments",
    COMMISSIONS: "commissions",
    REPORTS: "reports",
    MEMBER_ADD: "/memberadd",
};
