export enum EnrollmentMethodType {
    AGENT_ASSISTED_F2F = "AGENT_ASSISTED_F2F",
    CALL_CENTER = "CALL_CENTER",
    TELEPHONE_ENROLLMENT = "TELEPHONE_ENROLLMENT",
    SELF_SERVICE = "SELF_SERVICE",
    INDIVIDUAL_UNIVERSAL_CALL_CENTER = "INDIVIDUAL_UNIVERSAL_CALL_CENTER",
    VIRTUAL_F2F = "VIRTUAL_F2F",
}
