export enum PendingEnrollmentReason {
    CARRIER_APPROVAL = "CARRIER_APPROVAL",
    ADMIN_APPROVAL = "ADMIN_APPROVAL",
    CUSTOMER_SIGNATURE = "CUSTOMER_SIGNATURE",
    PDA_COMPLETION = "PDA_COMPLETION",
    THIRD_PARTY_APPROVAL = "THIRD_PARTY_APPROVAL",
    INCOMPLETE_MISSING_EAA = "INCOMPLETE_MISSING_EAA",
}
