export enum BUSINESS_ENROLLMENT_FEED_STATUS {
    AWAITING_TRANSMISSION = "AWAITING_TRANSMISSION",
    PROCESSING = "PROCESSING",
    SENT = "SENT",
    ERROR = "ERROR",
    CANCELED = "CANCELED",
    RENDERING_REQUIRED = "RENDERING_REQUIRED",
}
