export enum BusinessEnrollmentApplicationStatus {
    COMPLETE = "COMPLETE",
    INCOMPLETE_PENDING_SUBSCRIBER_APPROVAL = "INCOMPLETE_PENDING_SUBSCRIBER_APPROVAL",
    INCOMPLETE_PENDING_THIRD_PARTY_APPROVAL = "INCOMPLETE_PENDING_THIRD_PARTY_APPROVAL",
    INCOMPLETE_PENDING_PDA = "INCOMPLETE_PENDING_PDA",
    INCOMPLETE_MISSING_EAA = "INCOMPLETE_MISSING_EAA",
}
