export enum RULE_CONSTANT {
    WRITING_PRODUCER = "WRITING_PRODUCER",
    PRODUCT = "PRODUCT",
    CARRIER = "CARRIER",
    STATES = "STATES",
    DATE_WRITTEN = "DATE_WRITTEN",
    ENROLLMENT_METHOD = "ENROLLMENT_METHOD",
}
