import { EnrollmentMethod } from "../enums";
import { AccountProducerList } from "./account-producer-list-model";
import { AflacAlways } from "./aflac-always-model";
import { ApiError, GetPlan, PlanYear } from "./api";
import { Application } from "./application.model";
import { BasePlanApplicationPanel } from "./base-plan-application-panel-model";
import { CustomRiskClass } from "./custom-risk-class-model";
import { DirectPaymentCost } from "./direct-payment-cost-model";
import { EnrollmentInformation } from "./enrollment-info.model";
import { Enrollments } from "./enrollments.model";
import { MemberFlexDollar } from "./flex-dollar.model";
import { GetCartItems } from "./getCartItems.model";
import { GroupAttribute } from "./group-attribute.model";
import { HashKeys } from "./hash-keys-model";
import { MemberBeneficiary } from "./member-benficiary.model";
import { MemberContact } from "./member-contact.model";
import { MemberData } from "./member-data-model";
import { MemberDependent } from "./member-dependent.model";
import { MemberQualifyingEvent } from "./member-qualifying-life-event.model";
import { Relations } from "./member-relations.model";
import { PayFrequency } from "./pay-frequency.model";
import { PaymentCost } from "./payment-cost-model";
import { Payments } from "./payments-model";
import { PlanCoverageLevelRules } from "./plan-coverage-level-rules-model";
import { PlanOfferingPanel } from "./planOfferingPanel.model";
import { ProductOfferingPanel } from "./productOfferingPanel.model";
import { Reinstate } from "./reinstate-model";
import { ResponseItem } from "./response-item-model";
import { Responses } from "./responses-model";
import { SalaryDetails } from "./salary-details-model";
import { StepConstraints } from "./step-constraints-model";
import { EBS_Payment } from "./ebs-payment-model";

export interface EnrollmentStateModel {
    memberAge: number;
    knockOutData: any[];
    memberName: string;
    memberDependents: MemberDependent[];
    memberBeneficiaries: MemberBeneficiary[];
    mpGroup: number;
    memberId: number;
    payFrequency: PayFrequency;
    allPlanOfferings: PlanOfferingPanel[];
    productOfferings: ProductOfferingPanel[];
    navType: string;
    applications: Application[];
    cartItems: GetCartItems[];
    applicationResponse: Responses[];
    allPlans: GetPlan[];
    applicationPanel: BasePlanApplicationPanel[];
    appResponseItems: ResponseItem[];
    enrollmentMethod: EnrollmentMethod;
    enrollmentState: string;
    enrollments: Enrollments[];
    exitPopupStatus: boolean;
    constraints: StepConstraints[];
    baseRules: PlanCoverageLevelRules[];
    riderRulesRepo: PlanCoverageLevelRules[];
    memberData: MemberData;
    carrierRiskClasses: CustomRiskClass[];
    aflacAlways: AflacAlways[];
    totalPaymentCost: PaymentCost;
    reinstatementPanel: BasePlanApplicationPanel[];
    responseHashKeys: HashKeys[];
    payments: Payments[];
    directPaymentCost: DirectPaymentCost;
    ssnValue: string;
    email: [];
    preferredContactTime: string;
    memberContactData: MemberContact;
    employeeId: string;
    accountType: GroupAttribute[];
    companyProductsDisplayed: boolean;
    productPlanData: ProductOfferingPanel[];
    dependentRelation: Relations[];
    isOpenEnrollment: boolean;
    isQLEPeriod: boolean;
    currentQLE: MemberQualifyingEvent;
    reinstateItem: Reinstate;
    isDirect: boolean;
    memberFlexDollars: MemberFlexDollar[];
    enrollmentInfo: EnrollmentInformation;
    qleResponse: MemberQualifyingEvent[];
    salaryDetails: SalaryDetails;
    isPlanListPage: boolean;
    producerList: AccountProducerList;
    apiError: ApiError;
    cartItemId: number;
    companyProductsAcknowledgedMembers: number[];
    openEnrollmentPlanYears: PlanYear[];
    ebsPayment: EBS_Payment;
}
